# Plain data (no Django imports) shared by the seed command and the image generator.
EVENTS = [
 dict(title="Code and Coffee: Django Meetup", category="tech", city="Islamabad", venue="National Incubation Center", days=3, hour=17, price=0, capacity=60, sold=18,
      description="An evening for Python and Django developers. Short lightning talks, live demos and plenty of chai. Bring your laptop and your questions."),
 dict(title="AI and Data Science Summit", category="tech", city="Lahore", venue="Expo Centre Lahore", days=12, hour=10, price=1500, capacity=200, sold=120,
      description="A full-day summit on machine learning, data engineering and real projects from Pakistani teams. Includes lunch and a networking session."),
 dict(title="Sufi Night: Live Qawwali", category="music", city="Lahore", venue="Alhamra Arts Council", days=6, hour=20, price=2000, capacity=150, sold=140,
      description="A soulful evening of qawwali and Sufi kalam performed live under the open sky. Seating is limited."),
 dict(title="Unplugged Acoustic Evening", category="music", city="Karachi", venue="Frere Hall Lawn", days=9, hour=19, price=1200, capacity=120, sold=45,
      description="Local singers and guitarists perform stripped-down versions of favourite Urdu and Punjabi songs."),
 dict(title="Watercolour Workshop for Beginners", category="art", city="Islamabad", venue="Pakistan National Council of the Arts", days=5, hour=15, price=2500, capacity=20, sold=20,
      description="Learn washes, blending and simple landscapes with a professional artist. All materials are provided."),
 dict(title="Calligraphy and Truck Art Showcase", category="art", city="Karachi", venue="Indus Valley Gallery", days=15, hour=16, price=500, capacity=80, sold=22,
      description="An exhibition of Urdu calligraphy and hand-painted truck art, with live painting and a small craft bazaar."),
 dict(title="Inter-University Futsal Cup", category="sports", city="Rawalpindi", venue="Pindi Sports Arena", days=8, hour=14, price=300, capacity=150, sold=60,
      description="Eight university teams compete over one afternoon. Come to cheer, snack and enjoy the final under the lights."),
 dict(title="Sunday Morning 10K Run", category="sports", city="Islamabad", venue="Margalla Hills Trailhead", days=18, hour=7, price=800, capacity=300, sold=96,
      description="A friendly 10K run with timing chips, water stations and finisher medals. All levels welcome."),
 dict(title="Desi Street Food Festival", category="food", city="Lahore", venue="Gaddafi Stadium Grounds", days=10, hour=18, price=500, capacity=500, sold=210,
      description="Over thirty stalls serving golgappay, chargha, seekh kabab, kulfi and more. Live music and family seating."),
 dict(title="Biryani Masterclass with Chef Rizwan", category="food", city="Karachi", venue="The Cooking Studio, Clifton", days=7, hour=12, price=3000, capacity=15, sold=13,
      description="Cook a layered chicken biryani from scratch and learn the secrets of dum. You take your biryani home."),
 dict(title="Startup Pitch Night", category="business", city="Islamabad", venue="The Hive Co-working", days=4, hour=18, price=0, capacity=100, sold=40,
      description="Ten early-stage founders pitch to a panel of investors and mentors. Open networking after the session."),
 dict(title="Freelancing 101: Earn from Home", category="business", city="Online", venue="Zoom (link sent after registration)", days=11, hour=21, price=0, capacity=250, sold=75,
      description="A practical webinar on choosing a skill, building a profile, finding clients and getting paid internationally."),
 dict(title="Public Speaking Workshop", category="workshop", city="Lahore", venue="LUMS Seminar Hall", days=14, hour=11, price=1000, capacity=30, sold=12,
      description="Overcome stage fear, structure a talk and deliver with confidence. Includes live feedback."),
 dict(title="Resume and LinkedIn Clinic", category="workshop", city="Islamabad", venue="Air University Auditorium", days=20, hour=13, price=0, capacity=40, sold=9,
      description="Bring your CV and get one-to-one feedback. We also fix LinkedIn profiles and talk about internships."),
]
